# Generated by Django 5.0.6 on 2024-07-18 08:35

from django.db import migrations
import openpyxl
from django.core.exceptions import ValidationError

def insert_airports(apps, schema_editor):
    Airport = apps.get_model('parcel', 'Airport')
    
    try:
        # Load data from Excel workbook
        wb = openpyxl.load_workbook('parcel/data/kia.xlsx')
        sheet = wb['Airport']
        
        # Extract airport names from the Excel sheet
        airports_data = []
        for row in sheet.iter_rows(min_row=2, values_only=True):  # Assuming data starts from second row
            airport_name = row[0]  # Assuming airport name is in the first column
            airports_data.append({'airport_name': airport_name})
        
        # Insert data into the model
        for data in airports_data:
            try:
                Airport.objects.create(**data)
            except ValidationError as e:
                print(f"Validation Error: {e}")
    except FileNotFoundError:
        print("File not found. Please check the path to the Excel file.")
    except Exception as e:
        print(f"An error occurred: {e}")

class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_airports)
    ]
